// Vite plugin that turns the build into an installable, offline-ready PWA.
//
// - App icons are drawn in code (src/heaven/art/icon.ts) and emitted as PNGs,
//   so the repo holds no icon files.
// - The web app manifest launches the game standalone, with no fixed
//   orientation: on some phones (Xiaomi HyperOS) an installed app with one
//   never opens. Landscape comes from the loading screen's tap to start
//   instead (src/pwa.ts).
// - A small service worker precaches every file in the build, so the game
//   loads offline and starts instantly on later launches. Its caches are
//   named 'heaven-<version>', and it only ever clears old ones of that name.
//
// - notes.json: the patch notes (src/heaven/patchNotes.ts), left out of the
//   precache so a running game always fetches the deployed one and can show
//   what an update brings before it's taken (src/heaven/updates.ts).
//
// - The loading screen (inline in index.html) gets the game's title logo as
//   a PNG and the pixel font's letters, so it can show both before the game
//   itself has loaded.
//
// In dev the icons, logo and manifest are served from memory; the service worker is
// only registered in production builds.

import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Plugin, ResolvedConfig } from 'vite';
import { GLYPHS } from '../src/art/glyphs';
import { ICONS, renderIcon } from '../src/heaven/art/icon';
import { LOGO_FRAMES, heavenLogo } from '../src/heaven/art/logo';
import { PATCH_NOTES } from '../src/heaven/patchNotes';
import { encodePNG } from './png';

/** Heaven Lands' dawn: the peach its loading screen and install splash open on. */
const BG = '#f6cfc4';

// No orientation, for the reason above.
function manifest() {
  return {
    id: './',
    name: 'Heaven Lands',
    short_name: 'Heaven Lands',
    description: 'A cozy pixel world to build, grow and wander with friends.',
    start_url: './',
    scope: './',
    display: 'standalone',
    background_color: BG,
    theme_color: BG,
    categories: ['games'],
    icons: ICONS.filter((i) => !i.name.startsWith('apple') && !i.name.startsWith('favicon')).map((i) => ({
      src: `icons/${i.name}`,
      sizes: `${i.size}x${i.size}`,
      type: 'image/png',
      purpose: i.purpose,
    })),
  };
}

/** The title logo's frames, stacked top to bottom, for the loading screen. */
const LOGO_FILE = 'loader/logo.png';
/** The patch notes, never precached. */
const NOTES_FILE = 'notes.json';
const notesJSON = () => JSON.stringify(PATCH_NOTES);

const HEAD_TAGS = [
  { tag: 'link', attrs: { rel: 'preload', as: 'image', href: LOGO_FILE } },
  { tag: 'link', attrs: { rel: 'manifest', href: 'manifest.webmanifest' } },
  { tag: 'link', attrs: { rel: 'icon', type: 'image/png', sizes: '32x32', href: 'icons/favicon-32.png' } },
  { tag: 'link', attrs: { rel: 'apple-touch-icon', sizes: '180x180', href: 'icons/apple-touch-icon.png' } },
];

// The service worker. Navigations go network-first so a new deploy is picked
// up on the next launch; everything else is served from the precache.
const swSource = (version: string, files: string[]) => `// Generated by scripts/pwa.ts
const CACHE = 'heaven-${version}';
const FILES = ${JSON.stringify(['./', ...files.map((f) => `./${f}`)])};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  // Only this game's own old caches.
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE && /^heaven-/.test(k)).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  if (req.mode === 'navigate') {
    e.respondWith(
      fetch(req)
        .then((res) => {
          const copy = res.clone();
          if (res.ok) caches.open(CACHE).then((c) => c.put('./', copy));
          return res;
        })
        .catch(() => caches.match('./', { cacheName: CACHE })),
    );
    return;
  }
  e.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)));
});
`;

/** A short hash of the built files and their contents, naming the cache. */
function versionOf(files: string[], bundle: Record<string, { type: string; code?: string; source?: string | Uint8Array }>): string {
  const hash = createHash('sha256');
  for (const f of files) {
    const item = bundle[f];
    hash.update(f);
    hash.update(item.type === 'chunk' ? item.code! : item.source!);
  }
  return hash.digest('hex').slice(0, 12);
}

export function pwa(): Plugin {
  let config: ResolvedConfig;
  const icons = new Map<string, Buffer>();
  let logo: { png: Buffer; w: number; h: number } | null = null;
  const logoPNG = () => {
    if (!logo) {
      const l = heavenLogo();
      logo = { png: encodePNG(l.sheet.w, l.sheet.h, l.sheet.data), w: l.frameW, h: l.frameH };
    }
    return logo;
  };
  const iconPNG = (name: string) => {
    let png = icons.get(name);
    if (!png) {
      const spec = ICONS.find((i) => i.name === name);
      if (!spec) return undefined;
      png = encodePNG(spec.size, spec.size, renderIcon(spec));
      icons.set(name, png);
    }
    return png;
  };

  return {
    name: 'heaven-pwa',
    configResolved(c) {
      config = c;
    },
    transformIndexHtml() {
      // What the loading screen needs before the game has loaded: the logo's size and the font's letters.
      const { w, h } = logoPNG();
      const boot = `window.__BOOT=${JSON.stringify({ logo: { src: LOGO_FILE, w, h, frames: LOGO_FRAMES }, glyphs: GLYPHS })};`;
      return [{ tag: 'script', children: boot, injectTo: 'head-prepend' as const }, ...HEAD_TAGS.map((t) => ({ ...t, injectTo: 'head' as const }))];
    },
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url ?? '').split('?')[0];
        if (url.endsWith('/manifest.webmanifest')) {
          res.setHeader('Content-Type', 'application/manifest+json');
          res.end(JSON.stringify(manifest(), null, 2));
          return;
        }
        if (url.endsWith(`/${NOTES_FILE}`)) {
          res.setHeader('Content-Type', 'application/json');
          res.end(notesJSON());
          return;
        }
        if (url.endsWith(`/${LOGO_FILE}`)) {
          res.setHeader('Content-Type', 'image/png');
          res.end(logoPNG().png);
          return;
        }
        const icon = url.match(/\/icons\/([\w-]+\.png)$/);
        const png = icon && iconPNG(icon[1]);
        if (png) {
          res.setHeader('Content-Type', 'image/png');
          res.end(png);
          return;
        }
        next();
      });
    },
    generateBundle() {
      for (const spec of ICONS) this.emitFile({ type: 'asset', fileName: `icons/${spec.name}`, source: iconPNG(spec.name)! });
      this.emitFile({ type: 'asset', fileName: LOGO_FILE, source: logoPNG().png });
      this.emitFile({ type: 'asset', fileName: 'manifest.webmanifest', source: JSON.stringify(manifest(), null, 2) });
      this.emitFile({ type: 'asset', fileName: NOTES_FILE, source: notesJSON() });
    },
    writeBundle(_opts, bundle) {
      // Runs after every file is written, so the precache list is complete.
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map') && f !== NOTES_FILE).sort();
      const outDir = resolve(config.root, config.build.outDir);
      writeFileSync(resolve(outDir, 'sw.js'), swSource(versionOf(files, bundle), files));
    },
  };
}
